all:
	gcc -Wall -W -g -DMSGNO -lmba -o bindiff bindiff.c
	gcc -Wall -W -DMSGNO -lmba -o hexdiff hexdiff.c
	gcc -Wall -W -DMSGNO -lmba -o strdiff strdiff.c
	gcc -Wall -W -g -DMSGNO -lmba -o spell spell.c
clean:
	rm -f bindiff hexdiff strdiff spell
